# SPDX-FileCopyrightText: 2026 PythonWoods <dev@pythonwoods.dev>
# SPDX-License-Identifier: Apache-2.0
"""An opt-in code's flag must be honoured by every path that can emit it.

`CodeDefinition.activation`/`activation_key` declare which codes are opt-in.
Nothing applied that declaration: `templates.py` and `explain` read the fields to
*enumerate*, and each check then wrote its own `if config.policies.<key>`. Of the
five other `CodeDefinition` fields, `severity` has the central `code_severity()`
accessor and a test, and `fixable` has `test_fixable_code_wiring_structural.py`.
`activation` had neither, and drifted.

It drifted in `Z503`. `b70a0e6` put the gate in `validate_snippets` and said so in
its own message -- "rather than at its three call sites, so the Language Server
inherits it: a flag the CLI honours and the editor does not is two behaviours".
The server drives `IncrementalAnalysisEngine`, which calls the
`check_snippet_content` primitive directly and never reaches that wrapper. So the
editor reported a code `zenzic check` suppressed, for a year of releases, and that
is how `docs/rules/Z111.md` shipped a `.zenzic.toml` example declaring `docs_dir`
twice: the editor said so and CI did not.

**Behavioural rather than static, deliberately.** An AST sweep for
``if config.policies.<key>`` would have passed on the defect: the key *was*
present in `validator.py`. What was absent was a gate on a second call path, and
only running both paths can see that.

**The set is derived, and the fixtures are asserted to cover it.** A tenth opt-in
code added later has no fixture, so `test_every_opt_in_code_has_a_fixture` fails
and the corpus must be extended before the gate assertion can pass vacuously --
a zero-result sweep is not evidence until the instrument has been shown to find
something.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from typer.testing import CliRunner

from zenzic.core.adapters import get_adapter
from zenzic.core.codes import CODE_DEFINITIONS
from zenzic.core.incremental import IncrementalAnalysisEngine
from zenzic.core.scanner import _build_rule_engine
from zenzic.main import app
from zenzic.models.config import ZenzicConfig
from zenzic.models.vsm import VirtualBufferOverlay, build_vsm


runner = CliRunner()

#: Every code the registry declares opt-in. Derived, never restated: a literal
#: list here would agree today and stop agreeing the moment a code is added.
FLAG_CODES: frozenset[str] = frozenset(
    code for code, defn in CODE_DEFINITIONS.items() if defn.activation == "flag"
)

_FILLER = " ".join(["word"] * 55)

#: One markdown page per opt-in code, each written to trigger exactly that code.
#: The mapping's *keys* are checked against `FLAG_CODES`, so this cannot silently
#: fall behind the registry.
_FIXTURES: dict[str, tuple[str, str]] = {
    "Z106": (
        "alpha.md",
        f"# Alpha\n\n[Beta](beta.md) and [Index](index.md). {_FILLER}\n",
    ),
    "Z401": ("sub/page.md", f"# Nested\n\nA page in a directory with no index. {_FILLER}\n"),
    "Z411": ("sub/page.md", ""),  # same page: it links nowhere, so it dead-ends
    "Z502": ("short.md", "# Short\n\nToo short.\n"),
    "Z503": (
        "snip.md",
        f'# Snip\n\n[Index](index.md). {_FILLER}\n\n```toml\na = "x"\na = "y"\n```\n',
    ),
    "Z511": (
        "longsent.md",
        "# Longsent\n\n[Index](index.md), and this sentence is deliberately extended well "
        "past any reasonable threshold because it keeps going and going with clause after "
        "clause joined by commas and conjunctions so that the sentence length check has "
        "something wholly unambiguous to report whenever somebody switches it on.\n",
    ),
    "Z513": (
        "dupe.md",
        f"# Dupe\n\n[Index](index.md). {_FILLER}\n\n## Same Heading\n\nBody text here that "
        f"fills the section. {_FILLER}\n\n## Same Heading\n\nMore body text for the second "
        f"section. {_FILLER}\n",
    ),
    "Z517": (
        "punct.md",
        f"# Punct\n\n[Index](index.md). {_FILLER}\n\n## This heading ends with a period.\n\n"
        f"Body text that fills the section. {_FILLER}\n",
    ),
    "Z518": (
        "passive.md",
        f"# Passive\n\n[Index](index.md). The configuration was written by the maintainer "
        f"and the report was generated by the tool. {_FILLER}\n",
    ),
}


def _policies_block(enabled: bool) -> str:
    keys = sorted(
        defn.activation_key
        for defn in CODE_DEFINITIONS.values()
        if defn.activation == "flag" and defn.activation_key
    )
    body = "\n".join(f"{key} = {str(enabled).lower()}" for key in keys)
    return f'docs_dir = "docs"\n\n[policies]\n{body}\n'


def _build_corpus(tmp_path: Path, *, flags: bool) -> tuple[Path, Path]:
    docs = tmp_path / "docs"
    (docs / "sub").mkdir(parents=True, exist_ok=True)
    links = " ".join(f"[{i}]({rel})" for i, (rel, _) in enumerate(sorted(set(_FIXTURES.values()))))
    (docs / "index.md").write_text(f"# Index\n\n{links}\n\n{_FILLER}\n", encoding="utf-8")
    (docs / "beta.md").write_text(
        f"# Beta\n\n[Alpha](alpha.md) and [Index](index.md). {_FILLER}\n", encoding="utf-8"
    )
    for rel, body in _FIXTURES.values():
        if body:
            (docs / rel).write_text(body, encoding="utf-8")
    (tmp_path / ".zenzic.toml").write_text(_policies_block(flags), encoding="utf-8")
    return tmp_path, docs


def _cli_codes(repo_root: Path, monkeypatch: pytest.MonkeyPatch) -> set[str]:
    monkeypatch.chdir(repo_root)
    result = runner.invoke(app, ["check", "all", "--format", "sarif"])
    assert result.exit_code in (0, 1, 2, 3), f"CLI crashed (exit {result.exit_code})"
    sarif = json.loads(result.stdout)
    return {r["ruleId"] for r in sarif["runs"][0]["results"]}


def _engine_codes(repo_root: Path, docs_root: Path) -> set[str]:
    """Raw `IncrementalAnalysisEngine` output -- what the LSP and `zenzic-mcp` consume.

    Deliberately unfiltered. The parity harness drops the topology family and the
    `info` tier because it *compares* two shapes; this test asks a different
    question -- did the engine compute a finding it was told not to -- and a
    finding dropped later by one transport is still a gate that did not hold for
    the other.
    """
    config, _ = ZenzicConfig.load(repo_root)
    rule_engine = _build_rule_engine(config, containers=None)
    assert rule_engine is not None
    adapter = get_adapter(config.build_context, docs_root, repo_root)
    md = {p: p.read_text(encoding="utf-8") for p in docs_root.rglob("*.md")}
    vsm = build_vsm(
        adapter,
        docs_root,
        md,
        anchors_cache={p: set() for p in md},
        extra_mounts=[],
        static_assets=set(),
    )
    engine = IncrementalAnalysisEngine(
        config=config,
        rule_engine=rule_engine,
        adapter=adapter,
        docs_root=docs_root,
        repo_root=repo_root,
    )
    results = engine.process_changes(vsm, VirtualBufferOverlay(vsm, tabs=None))
    return {d.code for diags in results.values() for d in diags}


def test_every_opt_in_code_has_a_fixture() -> None:
    """A code with no fixture would make the gate assertion pass for free."""
    assert set(_FIXTURES) == FLAG_CODES, (
        "`_FIXTURES` must cover exactly the registry's opt-in codes. Missing: "
        f"{sorted(FLAG_CODES - set(_FIXTURES))}; stale: {sorted(set(_FIXTURES) - FLAG_CODES)}. "
        "A new opt-in code needs a page that triggers it before this module can "
        "claim to have checked its gate."
    )


def test_the_corpus_triggers_every_opt_in_code(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Positive control: with the flags on, the CLI reports all of them.

    Without this, `test_no_opt_in_code_is_emitted_while_its_flag_is_off` proves
    only that the corpus is uninteresting.
    """
    repo_root, _ = _build_corpus(tmp_path, flags=True)
    emitted = _cli_codes(repo_root, monkeypatch)
    missing = sorted(FLAG_CODES - emitted)
    assert not missing, (
        f"the corpus no longer triggers {missing}, so their gates are untested. "
        "Fix the fixture rather than the assertion."
    )


def test_no_opt_in_code_is_emitted_while_its_flag_is_off(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The gate, on both paths. This is the assertion `Z503` failed.

    Run against the same corpus the positive control above exercises, so a code
    absent here is absent because it was gated, not because nothing asked for it.
    """
    repo_root, docs_root = _build_corpus(tmp_path, flags=False)

    cli_leaks = sorted(_cli_codes(repo_root, monkeypatch) & FLAG_CODES)
    assert not cli_leaks, f"`zenzic check` emitted opt-in codes with their flags off: {cli_leaks}"

    engine_leaks = sorted(_engine_codes(repo_root, docs_root) & FLAG_CODES)
    assert not engine_leaks, (
        f"IncrementalAnalysisEngine -- the Language Server's and zenzic-mcp's -- emitted "
        f"opt-in codes with their flags off: {engine_leaks}. A flag the CLI honours and "
        "the editor does not is two behaviours, which is the defect this module exists for."
    )
