# SPDX-FileCopyrightText: 2026 PythonWoods <dev@pythonwoods.dev>
# SPDX-License-Identifier: Apache-2.0
"""Base adapter contract for all documentation engines.

ADR-078-STRICT hardens the adapter API from structural Protocol typing to a
runtime-enforced ABC contract. Every first-party and third-party adapter must
subclass :class:`BaseAdapter`.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Literal

import pathspec.gitignore

from zenzic.core.extensions import DEFAULT_EXTENSIONS, EnabledExtensions


if TYPE_CHECKING:
    from zenzic.models.vsm import RouteStatus, VirtualSiteMap


# ── Route metadata types ─────────────────────────────────────────────────────


VirtualRouteKind = Literal[
    "tag", "tag_index", "pagination", "author", "author_index", "category_index"
]


@dataclass(frozen=True, slots=True)
class VirtualRoute:
    """A route generated by the build engine without a physical markdown file."""

    url: str
    label: str
    source_files: frozenset[str]
    kind: VirtualRouteKind

    def __post_init__(self) -> None:
        if not self.source_files:
            raise ValueError(
                f"VirtualRoute {self.url!r}: source_files is empty — "
                "Reverse-Mapping Invariant violated"
            )


@dataclass(slots=True)
class RouteMetadata:
    """Unified route information for one source file."""

    canonical_url: str
    status: RouteStatus
    slug: str | None = None
    route_base_path: str = "/"
    is_proxy: bool = False
    version: str | None = None


# ── Adapter contract ─────────────────────────────────────────────────────────


class BaseAdapter(ABC):
    """Runtime-enforced adapter contract used by scanner, validator, and VSM."""

    @abstractmethod
    def is_locale_dir(self, part: str) -> bool:
        """Return ``True`` when *part* is a non-default locale directory name."""

    @abstractmethod
    def resolve_asset(self, missing_abs: Path, docs_root: Path) -> Path | None:
        """Return default-locale fallback for a missing asset, else ``None``."""

    @abstractmethod
    def resolve_anchor(
        self,
        resolved_file: Path,
        anchor: str,
        anchors_cache: dict[Path, set[str]],
        docs_root: Path,
    ) -> bool:
        """Return ``True`` when an anchor miss should be suppressed via i18n fallback."""

    @abstractmethod
    def is_shadow_of_nav_page(self, rel: Path, nav_paths: frozenset[str]) -> bool:
        """Return ``True`` when *rel* mirrors a nav-listed default-locale page."""

    @abstractmethod
    def get_ignored_patterns(self) -> set[str]:
        """Return filename glob patterns ignored by orphan detection."""

    @abstractmethod
    def get_nav_paths(self) -> frozenset[str]:
        """Return nav-listed markdown paths relative to ``docs_root``."""

    @abstractmethod
    def has_engine_config(self) -> bool:
        """Return ``True`` when engine config exists and nav-based checks are meaningful."""

    @abstractmethod
    def get_metadata_files(self) -> frozenset[str]:
        """Return engine-owned config filenames excluded from quality findings."""

    def declared_sources(self) -> set[str] | None:
        """Return the source paths this adapter's routing table **declares**, or
        ``None`` when routes are derived from the filesystem instead.

        Only a declarative adapter can be stale, and the distinction is the
        whole point of this method. ``standalone`` computes each URL from the
        path it has just read: there is no second copy to fall behind, so drift
        is not a state it can reach and a drift finding there would be one no
        user could act on. ``prebuilt`` reads ``.zenzic-vsm.json``, written by
        a separate tool at a separate time, and that copy goes stale the moment
        someone adds a page without re-running the generator.

        Measured before this method existed: a source absent from the manifest
        is routed ``IGNORED`` by :class:`PrebuiltVSMAdapter`, and a link whose
        target is IGNORED is reported ``Z101 ... UNREACHABLE_LINK``. So adding
        a page and linking to it produced an error on a link that was correct,
        and the run named the link rather than the manifest. The engine held
        both sets — what the manifest declares, what the scan read — and
        compared them nowhere.

        Returning ``None`` (the default) means "not a declarative table, never
        stale", which is not the same as returning an empty set — that would
        mean "declares nothing", i.e. total drift.
        """
        return None

    def get_enabled_extensions(self) -> EnabledExtensions:
        """Return the Markdown extensions this project enables.

        The adapter answers **which extensions are on**, because that is a fact
        about the project. What each one brings is `core/extensions.py`'s, because
        that is a fact about Markdown. MkDocs does not define ``!!!``; it enables
        `admonition`, and only when the project lists it.

        **The default is not the empty set, and this differs from**
        :meth:`get_output_dirs` **on purpose.** There, an engine declaring no
        output directory returns nothing rather than guessing, because a wrong
        guess excludes real content. Here the opposite is measured: an empty
        vocabulary makes the block tracker read **1,112 lines of our own corpus
        and 1,068 of `zensical/docs`** as indented code, which every rule that
        opts into `in_indented_code` then skips. Emptiness is the expensive
        answer, so an engine with no configuration to read inherits
        `DEFAULT_EXTENSIONS` instead.

        Measured 2026-09-18: on both corpora the default and the real reading
        produce the identical result, because both enable all four relevant
        extensions.
        """
        return EnabledExtensions(names=DEFAULT_EXTENSIONS)

    def get_output_dirs(self) -> frozenset[str]:
        """Return repo-relative directories this engine writes its built site to.

        Not abstract, and deliberately so: an engine that declares no output
        directory returns the empty set rather than a guess. Only MkDocs
        declares one (``site_dir``), so a default here keeps the other three
        adapters honest instead of making them implement a stub that invents
        ``"site"``.

        Paths are **repo-relative POSIX strings**, matched against the walk's
        ``rel_path`` rather than a basename. That distinction is the whole
        point: a name-based exclusion of ``site`` also excluded a legitimate
        ``docs/site/`` content directory, which measured as a `Z101` on a real
        fixture. A declared output directory is one specific path.
        """
        return frozenset()

    def get_excluded_docs_spec(self) -> pathspec.gitignore.GitIgnoreSpec | None:
        """Return a matcher for pages this engine keeps out of the built site.

        Not abstract, for the same reason as :meth:`get_output_dirs`: an engine
        with no such concept returns ``None`` rather than implementing a stub.
        Only MkDocs declares these (``exclude_docs``/``draft_docs``).

        A **matcher**, not a list of paths, and deliberately so. Enumerating the
        matches would mean walking the docs tree here, and every filesystem walk
        in the engine goes through ``discovery`` — that is the check keeping a
        config-derived root from reaching outside the repository. The exclusion
        manager applies this spec to each ``rel_path`` during the walk it already
        performs, exactly as it applies the VCS pathspec.
        """
        return None

    @abstractmethod
    def get_route_info(self, rel: Path) -> RouteMetadata:
        """Return canonical URL and route status metadata for ``rel``."""

    @abstractmethod
    def provides_index(self, directory_path: Path) -> bool:
        """Return whether the engine serves a landing page for ``directory_path``."""

    def get_link_scheme_bypasses(self) -> frozenset[str]:
        """Return URI schemes exempt from unknown-scheme and Z105 checks."""
        return frozenset()

    @abstractmethod
    def get_extra_content_roots(self, repo_root: Path) -> list[Path]:
        """Return additional markdown content roots outside ``docs_root``."""

    @abstractmethod
    def get_locale_source_roots(self, repo_root: Path) -> list[tuple[Path, str]]:
        """Return locale source roots as ``(root_path, locale_label)`` pairs."""

    def get_absolute_url_prefixes(self, repo_root: Path | None = None) -> list[str]:  # noqa: ARG002
        """Return project-owned absolute URL prefixes.

        **One authority, three consumers.** `Z105` allowlists what this returns
        (`rules.py`), `VSMBrokenLinkRule` re-bases against the same list so the
        two cannot disagree about where the site starts, and the path-traversal
        guard reads it on the incremental path (`incremental.py`) to decide
        whether a site-absolute link is exempt before `Z202`/`Z203` classify it.

        That third one was omitted when this said "two consumers", written the
        same day the method was introduced: the author looked in `rules.py` and
        not in `incremental.py`. It is the security-tier reader, so it is the one
        that most needed naming. Wiring only the first was measured
        on 2026-09-20 and rejected: `absolute_path_allowlist = ["/docs/"]` already
        cleared `Z105` alone and left every such link reported broken by `Z101`,
        which looks like a working feature and is not one.

        The list is set by `get_adapter` from `[build_context] base_url`, so an
        adapter that wants no prefix declares nothing rather than overriding. The
        one exception is `PrebuiltVSMAdapter`, whose routes already carry the real
        build's prefix; it refuses `base_url` at construction instead.
        """
        return list(getattr(self, "_zenzic_base_prefixes", ()))

    @property
    def dynamic_directories(self) -> set[Path]:
        """Return directories where the build engine dynamically generates landing pages or routing."""
        return set()

    @property
    def use_directory_urls(self) -> bool:
        """Return URL routing mode: ``True`` for ``/page/``, ``False`` for ``/page.html``."""
        return True

    @property
    def watched_config_files(self) -> frozenset[str]:
        """Return the configuration filenames that trigger a VSM rebuild in LSP mode."""
        return frozenset()

    @abstractmethod
    def get_entry_points(self, vsm: VirtualSiteMap) -> list[str]:
        """Return canonical URLs serving as root entry points for reachability analysis."""
