# SPDX-FileCopyrightText: 2026 PythonWoods <dev@pythonwoods.dev>
# SPDX-License-Identifier: Apache-2.0
# .zenzic.toml — Z615 FORBIDDEN_URL_SCHEME gallery example

docs_dir = "docs"
fail_under = 0

[build_context]
engine = "standalone"

[policies]
required_url_schemes = ["https", "mailto"]
