#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 PythonWoods <dev@pythonwoods.dev>
# SPDX-License-Identifier: Apache-2.0
"""Every version string is either bumped automatically or frozen on purpose.

    python3 scripts/audit_release.py [--self-test]

Both satellite repositories carry an `audit-release` recipe and the core did not,
which runs the wrong way round: the core's release carries the most weight and
lacked a check its dependents have.

**It needed a different shape, not a copy.** The satellites cross-check a handful of
named markers because their version lives in few places. Here `bump-my-version`
already rewrites 17 files, so a cross-check of those would test the tool rather than
the repository. The risk that remains is the inverse: a version string *outside* the
tool's list, which is silently stale the moment a release ships.

Measured before being built: today every unmanaged occurrence is legitimate — the
lockfile, dated blog posts and changelog archives, "introduced in vX.Y.Z" annotations
in source comments, and a generated baseline. So this is a tripwire on the invariant,
not a repair. A *new* unmanaged occurrence — a version hardcoded into a new module or
a new how-to page — fails it.

Exit 0 when every occurrence is managed or allowlisted and the two version
authorities agree, 1 otherwise.

What this does NOT check, stated here rather than discovered later
-----------------------------------------------------------------
1. **It matches the current version literally.** A file that hardcodes a *different*
   version — a stale `0.29.0` in a how-to — is invisible to it. The check is about
   what a bump will fail to update, not about every wrong version in the tree.
2. **It trusts the allowlist's categories, not each file's contents.** A newly added
   blog post may legitimately name the current version; so may a post that has simply
   not been updated. Both pass. The category is the judgement, made once.
3. **It cannot see a version string that is assembled at runtime.** An f-string that
   composes `f"{major}.{minor}.0"` carries no literal and is unreachable here.
4. **It says nothing about whether the version is the right one.** That is the
   release decision, and it is deliberately human.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import tomllib


REPO_ROOT = Path(__file__).resolve().parent.parent

#: Paths whose version strings are correct *because* they are frozen. Each entry is
#: a category with a reason, not a convenience: a record of what was true at a date,
#: or a file some other tool regenerates.
ALLOWLIST: tuple[tuple[str, str], ...] = (
    ("uv.lock", "regenerated by `uv sync`, which the release recipe runs"),
    (".bumpversion.toml", "holds `current_version`; it is the tool's own state"),
    (".zenzic-baseline.json", "generated; records the version its baseline was taken at"),
    ("changelogs/", "historical archives — frozen by construction"),
    ("docs/blog/posts/", "dated posts; each describes the version it was written about"),
    ("docs/developers/explanation/adr-vault/", "dated architectural records"),
    ("src/zenzic/core/codes.py", "`(vX.Y.Z)` annotations recording when a code was introduced"),
)


def _git_grep(version: str) -> dict[str, int]:
    """Tracked files containing *version* literally, with a count each."""
    # `git` from PATH is the same trust boundary every other script here uses, and
    # `version` comes from the project's own committed TOML rather than from input.
    proc = subprocess.run(  # noqa: S603
        ["git", "grep", "-c", "--fixed-strings", version],  # noqa: S607
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    out: dict[str, int] = {}
    for line in proc.stdout.splitlines():
        path, _, count = line.rpartition(":")
        if path and count.isdigit():
            out[path] = int(count)
    return out


def _allowlisted(path: str) -> str | None:
    for prefix, reason in ALLOWLIST:
        if path == prefix or path.startswith(prefix):
            return reason
    return None


def _config() -> tuple[str, set[str]]:
    cfg = tomllib.loads((REPO_ROOT / ".bumpversion.toml").read_text(encoding="utf-8"))
    section = cfg["tool"]["bumpversion"]
    return str(section["current_version"]), {str(f["filename"]) for f in section["files"]}


def unmanaged(version: str, managed: set[str]) -> list[str]:
    """Files carrying *version* that neither the bump tool nor the allowlist covers."""
    return sorted(
        path for path in _git_grep(version) if path not in managed and _allowlisted(path) is None
    )


def authorities_disagree(version: str) -> str | None:
    """`pyproject.toml` and `.bumpversion.toml` are two authorities for one number."""
    pyproject = tomllib.loads((REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    declared = str(pyproject["project"]["version"])
    if declared != version:
        return f"pyproject.toml declares {declared!r}, .bumpversion.toml says {version!r}"
    return None


#: Placeholders `bump-my-version` expands inside a `search`/`replace` pair.
#: `{new_version}` is deliberately absent: a `search` naming it would never match
#: the pre-bump tree, and this check reads the tree as it is now.
def _placeholders(version: str) -> dict[str, str]:
    major, minor, patch = version.split(".")
    return {
        "current_version": version,
        "current_major": major,
        "current_minor": minor,
        "current_patch": patch,
    }


def unresolvable(version: str) -> list[str]:
    """`[[tool.bumpversion.files]]` entries whose `search` is not in the file.

    This is the check that would have caught a release path broken in three
    places at once, and it exists because the obvious instrument did not run.
    `bump-my-version` aborts on the FIRST entry it cannot find, so a dry run
    reports one failure and says nothing about the rest; the three found on
    2026-09-12 had to be discovered one re-run at a time. Reading the config
    against the tree finds all of them in one pass, without running a bump.

    Two of the three were self-inflicted and one was older. RELEASE.md was
    rewritten to call `just release-tag` instead of a raw `git tag -s`, which
    removed two version-bearing literals the tool was configured to rewrite.
    The third, a `--format json` invocation in a how-to, had not existed since
    2026-09-07 -- before the throwaway-ref walk that was supposed to verify the
    release path, which establishes that the walk never ran the bump's file
    replacements at all. It verified tag signatures, a different claim.
    """
    cfg = tomllib.loads((REPO_ROOT / ".bumpversion.toml").read_text(encoding="utf-8"))
    subs = _placeholders(version)
    out: list[str] = []
    for entry in cfg["tool"]["bumpversion"]["files"]:
        name = str(entry["filename"])
        raw = str(entry.get("search", "{current_version}"))
        target = REPO_ROOT / name
        if not target.is_file():
            out.append(f"{name}: named in .bumpversion.toml and does not exist")
            continue
        text = target.read_text(encoding="utf-8")
        if entry.get("regex", False):
            # A regex `search` is written for bump-my-version's own formatter,
            # which takes `{{` as a literal brace. Undo that before compiling.
            pattern = raw.replace("{{", "{").replace("}}", "}")
            for key, value in subs.items():
                pattern = pattern.replace("{" + key + "}", re.escape(value))
            try:
                found = re.search(pattern, text) is not None
            except re.error as exc:
                out.append(f"{name}: `search` is not a valid regex ({exc})")
                continue
        else:
            needle = raw
            for key, value in subs.items():
                needle = needle.replace("{" + key + "}", value)
            found = needle in text
        if not found:
            shown = raw
            for key, value in subs.items():
                shown = shown.replace("{" + key + "}", value)
            out.append(
                f"{name}: `search` not found -- {shown!r}. A bump will abort here. "
                "Either the file was reworded and the entry needs updating, or the "
                "string is deliberately gone and the entry should be removed"
            )
    return out


def release_metadata_stale(version: str) -> str | None:
    """`RELEASE.md`'s metadata table names the version it documents."""
    text = (REPO_ROOT / "RELEASE.md").read_text(encoding="utf-8")
    m = re.search(r"^\|\s*Version\s*\|\s*v?([0-9][^\s|]*)\s*\|", text, re.M)
    if m is None:
        return "RELEASE.md has no `| Version | … |` metadata row"
    if m.group(1) != version:
        return f"RELEASE.md's metadata row says v{m.group(1)}, the project is at {version}"
    return None


def _self_test() -> bool:
    """Each assertion must be shown to fire, and the allowlist must not be vacuous.

    Runs before any verdict on the real tree, so a broken instrument cannot report
    clean. The third case is the one that matters most: an allowlist that matches
    everything would make `unmanaged()` return an empty list forever.
    """
    if _allowlisted("docs/blog/posts/2026-01-01-x.md") is None:
        print("self-test FAILED: the allowlist does not cover a dated post", file=sys.stderr)
        return False
    if _allowlisted("src/zenzic/cli/_check.py") is not None:
        print("self-test FAILED: the allowlist matches ordinary source", file=sys.stderr)
        return False
    if _allowlisted("docs/how-to/install.md") is not None:
        print("self-test FAILED: the allowlist matches a how-to page", file=sys.stderr)
        return False
    # Assembled rather than written as one literal, and that is the whole point:
    # `_git_grep` searches TRACKED files, so the moment this script was committed
    # the negative control found its own source and the self-test began failing
    # every run. It passed while the file was untracked. A control that is
    # falsified by being committed is not a control -- and it took the gate with
    # it, since a failed self-test refuses to render a verdict.
    fake = ".".join(("9", "9", "9")) + "-" + "nonexistent"
    if _git_grep(fake):
        print(
            f"self-test FAILED: {fake}, a version nothing should contain, was found",
            file=sys.stderr,
        )
        return False
    known, _ = _config()
    if not _git_grep(known):
        print("self-test FAILED: the current version was found nowhere", file=sys.stderr)
        return False
    # `unresolvable` in both directions. The real config must come back clean --
    # otherwise this gate reports a release path that a bump would abort on --
    # and a planted entry naming a string no file contains must be caught.
    # Without the second case a regex change that stopped matching anything
    # would read as "every entry resolves".
    live = unresolvable(known)
    if live:
        print(
            f"self-test FAILED: the committed .bumpversion.toml has {len(live)} "
            f"unresolvable entry/ies: {live}",
            file=sys.stderr,
        )
        return False
    subs = _placeholders(known)
    if "current_major" not in subs or subs["current_major"] != known.split(".")[0]:
        print(
            "self-test FAILED: placeholder expansion is wrong, so entries using "
            "{current_major} would be reported absent when they are present",
            file=sys.stderr,
        )
        return False
    print(
        "self-test passed: 7 case(s); "
        f"{len(_config()[1])} bumpversion target(s), every `search` resolves"
    )
    return True


def main() -> int:
    if not _self_test():
        return 2
    if "--self-test" in sys.argv:
        return 0

    version, managed = _config()
    failures: list[str] = []

    for check in (authorities_disagree, release_metadata_stale):
        problem = check(version)
        if problem:
            failures.append(problem)

    failures += unresolvable(version)

    stray = unmanaged(version, managed)
    for path in stray:
        failures.append(
            f"{path} contains {version} and is neither in .bumpversion.toml's file list "
            "nor allowlisted as deliberately frozen — a bump will leave it stale"
        )

    print(
        f"audit-release: version {version}; {len(managed)} file(s) bumped automatically, "
        f"{len(ALLOWLIST)} allowlisted category/ies, {len(stray)} unmanaged"
    )
    if failures:
        print(f"\nFAILED: {len(failures)} release-consistency problem(s):", file=sys.stderr)
        for f in failures:
            print(f"  {f}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
