#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 PythonWoods <dev@pythonwoods.dev>
# SPDX-License-Identifier: Apache-2.0
"""Every version string is either bumped automatically or frozen on purpose.

    python3 scripts/audit_release.py [--self-test]

Both satellite repositories carry an `audit-release` recipe and the core did not,
which runs the wrong way round: the core's release carries the most weight and
lacked a check its dependents have.

**It needed a different shape, not a copy.** The satellites cross-check a handful of
named markers because their version lives in few places. Here `bump-my-version`
already rewrites 17 files, so a cross-check of those would test the tool rather than
the repository. The risk that remains is the inverse: a version string *outside* the
tool's list, which is silently stale the moment a release ships.

Measured before being built: today every unmanaged occurrence is legitimate — the
lockfile, dated blog posts and changelog archives, "introduced in vX.Y.Z" annotations
in source comments, and a generated baseline. So this is a tripwire on the invariant,
not a repair. A *new* unmanaged occurrence — a version hardcoded into a new module or
a new how-to page — fails it.

Exit 0 when every occurrence is managed or allowlisted and the two version
authorities agree, 1 otherwise.

What this does NOT check, stated here rather than discovered later
-----------------------------------------------------------------
1. **It matches the current version literally.** A file that hardcodes a *different*
   version — a stale `0.29.0` in a how-to — is invisible to it. The check is about
   what a bump will fail to update, not about every wrong version in the tree.
2. **It trusts the allowlist's categories, not each file's contents.** A newly added
   blog post may legitimately name the current version; so may a post that has simply
   not been updated. Both pass. The category is the judgement, made once.
3. **It cannot see a version string that is assembled at runtime.** An f-string that
   composes `f"{major}.{minor}.0"` carries no literal and is unreachable here.
4. **It says nothing about whether the version is the right one.** That is the
   release decision, and it is deliberately human.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import tomllib


REPO_ROOT = Path(__file__).resolve().parent.parent

#: Paths whose version strings are correct *because* they are frozen. Each entry is
#: a category with a reason, not a convenience: a record of what was true at a date,
#: or a file some other tool regenerates.
ALLOWLIST: tuple[tuple[str, str], ...] = (
    ("uv.lock", "regenerated by `uv sync`, which the release recipe runs"),
    (".bumpversion.toml", "holds `current_version`; it is the tool's own state"),
    (".zenzic-baseline.json", "generated; records the version its baseline was taken at"),
    ("changelogs/", "historical archives — frozen by construction"),
    ("docs/blog/posts/", "dated posts; each describes the version it was written about"),
    ("docs/developers/explanation/adr-vault/", "dated architectural records"),
    ("src/zenzic/core/codes.py", "`(vX.Y.Z)` annotations recording when a code was introduced"),
)


def _git_grep(version: str) -> dict[str, int]:
    """Tracked files containing *version* literally, with a count each."""
    # `git` from PATH is the same trust boundary every other script here uses, and
    # `version` comes from the project's own committed TOML rather than from input.
    proc = subprocess.run(  # noqa: S603
        ["git", "grep", "-c", "--fixed-strings", version],  # noqa: S607
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    out: dict[str, int] = {}
    for line in proc.stdout.splitlines():
        path, _, count = line.rpartition(":")
        if path and count.isdigit():
            out[path] = int(count)
    return out


def _allowlisted(path: str) -> str | None:
    for prefix, reason in ALLOWLIST:
        if path == prefix or path.startswith(prefix):
            return reason
    return None


def _config() -> tuple[str, set[str]]:
    cfg = tomllib.loads((REPO_ROOT / ".bumpversion.toml").read_text(encoding="utf-8"))
    section = cfg["tool"]["bumpversion"]
    return str(section["current_version"]), {str(f["filename"]) for f in section["files"]}


def unmanaged(version: str, managed: set[str]) -> list[str]:
    """Files carrying *version* that neither the bump tool nor the allowlist covers."""
    return sorted(
        path for path in _git_grep(version) if path not in managed and _allowlisted(path) is None
    )


def authorities_disagree(version: str) -> str | None:
    """`pyproject.toml` and `.bumpversion.toml` are two authorities for one number."""
    pyproject = tomllib.loads((REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    declared = str(pyproject["project"]["version"])
    if declared != version:
        return f"pyproject.toml declares {declared!r}, .bumpversion.toml says {version!r}"
    return None


def release_metadata_stale(version: str) -> str | None:
    """`RELEASE.md`'s metadata table names the version it documents."""
    text = (REPO_ROOT / "RELEASE.md").read_text(encoding="utf-8")
    m = re.search(r"^\|\s*Version\s*\|\s*v?([0-9][^\s|]*)\s*\|", text, re.M)
    if m is None:
        return "RELEASE.md has no `| Version | … |` metadata row"
    if m.group(1) != version:
        return f"RELEASE.md's metadata row says v{m.group(1)}, the project is at {version}"
    return None


def _self_test() -> bool:
    """Each assertion must be shown to fire, and the allowlist must not be vacuous.

    Runs before any verdict on the real tree, so a broken instrument cannot report
    clean. The third case is the one that matters most: an allowlist that matches
    everything would make `unmanaged()` return an empty list forever.
    """
    if _allowlisted("docs/blog/posts/2026-01-01-x.md") is None:
        print("self-test FAILED: the allowlist does not cover a dated post", file=sys.stderr)
        return False
    if _allowlisted("src/zenzic/cli/_check.py") is not None:
        print("self-test FAILED: the allowlist matches ordinary source", file=sys.stderr)
        return False
    if _allowlisted("docs/how-to/install.md") is not None:
        print("self-test FAILED: the allowlist matches a how-to page", file=sys.stderr)
        return False
    fake = "9.9.9-nonexistent"
    if _git_grep(fake):
        print("self-test FAILED: a version nothing contains was found", file=sys.stderr)
        return False
    known, _ = _config()
    if not _git_grep(known):
        print("self-test FAILED: the current version was found nowhere", file=sys.stderr)
        return False
    print("self-test passed: 5 case(s)")
    return True


def main() -> int:
    if not _self_test():
        return 2
    if "--self-test" in sys.argv:
        return 0

    version, managed = _config()
    failures: list[str] = []

    for check in (authorities_disagree, release_metadata_stale):
        problem = check(version)
        if problem:
            failures.append(problem)

    stray = unmanaged(version, managed)
    for path in stray:
        failures.append(
            f"{path} contains {version} and is neither in .bumpversion.toml's file list "
            "nor allowlisted as deliberately frozen — a bump will leave it stale"
        )

    print(
        f"audit-release: version {version}; {len(managed)} file(s) bumped automatically, "
        f"{len(ALLOWLIST)} allowlisted category/ies, {len(stray)} unmanaged"
    )
    if failures:
        print(f"\nFAILED: {len(failures)} release-consistency problem(s):", file=sys.stderr)
        for f in failures:
            print(f"  {f}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
